# Midterm study Notebook

The problems in Part One are taken from a previous quiz.  Write the value of each expression in the space provided. A helpful reminder.  When applied to strings, '<' checks alphabetical order.  So

```
>>> 'a' < 'b'
True
>>> 'b' < 'a'
False
>>> 'a' < 'a'
False
```

When applied to strings '+' does concatenation:

```
>>> 'a' + 'x'
'ax'
```


## Part One

In [1]:
letters = 'abcdefghijklmnopqrstuvwxyz'
vowels = 'aeiou'
word = 'facetious'
X = [l for l in letters if l not in vowels]
Y = [x for x in letters if x > 'd' and x < 'j']
W = [x for x in letters if x < 'd' or x > 'j']
Z = [x > 'd' and x < 'j' for x in letters]
R = [x for x in word if x in vowels]
letter_classes = {'vowels': vowels, 'consonants': X}

In [4]:
Y

['e', 'f', 'g', 'h', 'i']

###### Preliminaries

Write out `X`.  Remember `X` was created by a list comprehension, so it must be a list.

Write out `Y`.  Remember `Y` filters the elements of `letters` with the condition `x > 'd' and x < 'j'`.

Write out `W`, also a filter.

Write out `Z`. Remember the expression to the left of `for` in the list comprehension is what is evaluated once for each element of `letters`, with the results collected in the list `Z`.  So `Z` will be a list of things of the same type as `x > 'd' and x < 'j'`.

Write out `R`. Remember `R` filters the elements of `word` with the condition `x in vowels`.

Write out `letter_classes`.  Remember `letter_classes` is a dictionary.  Use curly braces.  Separate the keys from the values with `:`.

1) What is the value of the following Python expression?

```
['b' + x for x in vowels]
```

In [5]:
['b' + x for x in vowels]

['ba', 'be', 'bi', 'bo', 'bu']

2) What is the value of the following Python expression?

```
Y[0]
```

3) What is the value of the following Python expression? (List splice must be a sublist of `X`)

```
X[0:2]
```

4) Write a Python expression which operates on `letters` and returns the following value

```
'ghi'
```

5) Write a Python expression which operates on `letters` and returns the following  value.

```
['g','h','i']
```

6) What is the value of the following Python expression?

```
Z[0:3]
```

7) Write a Python expression which operates on `Y` and returns the following value:

```
['e','i']
```

8) Write a line of code which operates on `Y` and returns `False`.

9) Write a line of code which returns the following value when applied to `vowels`:

```
[True, True, False, False, False]
```

10) Write a line of code which operates on `letter_classes` and returns the following value.

```
'e'
```

11) Write a line of code which operates on `letter_classes` and returns the following value.

```
'y'
```

12) What is the value of the following expression?

```
R[-1]
```

##       Part Two

Write functions that behave according to the descriptions given.

1) Write a function that takes two numbers as arguments and multiplies them together and adds 1 to the result.  Call your function `product_successor`.  Then:

```
>>> product_successor(3,2)
7
>>> product_successor(5,9)
46
```

In [11]:
def one_less_than_sq (x):
    return x**2 - 1

In [12]:
x = one_less_than_sq(3)

In [13]:
x

8

2) Write a function that returns a list of the vowels from any string passed in.  You should use the list `vowels` from Part One as part of your answer.

```
>>> extract_vowels('hoover')
['o','o','e']
```

## Part 3

Reminders: `range(n)` returns a list of the integers from 0 up to but not including `n`.

```
>>> range(10)
[0,1,2,3,4,5,6,7,8,9]
```

`'str0'.join(str_seq)`  returns a string gotten by joining together the elements of `str_seq` with `str0`. It is the opposite of `split`.  It is an error if the elements of `str_seq` are not all strings:

```
>>> ''.join(['a','b','c'])
'abc'
>>> 'x'.join(['a','b','c'])
'axbxc'
>>> 'x'.join([1,2,3])
TypeError      
...
TypeError: sequence item 0: expected string, int found
>>> 'i'.join(['m','ss','ss','pp',''])
'mississippi'
>>> 'i'.join(['m','ss','ss','pp'])
'mississipp'
```




In [ ]:
letters = ('a', 'b', 'c', 'd', 'e', 'f', 'g', 
           'h', 'i', 'j', 'k', 'l', 'm', 'n', 
           'o', 'p', 'q', 'r', 's', 't', 'u', 
           'v', 'w', 'x', 'y', 'z')
vowels = 'aeiou'
digits = list(range(4))
word_list = ['acre','loft', 'soap', 'pleat']
weird_list = [word_list[x][x] for x in digits]
word3 = ''.join([x[1] for x in word_list])
word4 = 'i'.join(['m','ss','ss','pp',''])
char_list = [x for x in word4 if x in vowels]
word1 = 'rambunctious'
word2 = 'mellifluous'
WW = word1 + word2
Z = [x for x in WW if x in 'lmn']
favorite_words = {'Noam Chomsky': word2, 'Leonard Bloomfield': word1, 'John Rupert Firth': word3}

Write out `word3` below.

Write out `word4` below.

Write out `digits` below.

Write out `weird_list` below.

Write out `char_list` below.

Write out `Z` below.

Write an expression which operates on `favorite_word` and returns:

```
'cool'
```

Write an expression which operates on `favorite_word` and returns:

```
'bun'
```

Hint: Use a splice.  Remember that `favorite_word` is a dictionary. Values are retrieved from a dictionary by keys, and therefore it makes no sense to use numerical indices (or splices) directly on a dictionary.  But you might be able to use a splice on something inside the dictionary.

Write an expression which retrieves

```
['a','b','c','x','y''z']
```

from `letters`.  Hint: use a list comprehension with a condition.

## Part 4

In [ ]:
employees = ['happy', 'sleepy', 'dopey', 'bashful', 'grumpy', 'doc', 'sneezy']
employeeEmail = {'happy': ['sleepy','dopey'], 'dopey':['dopey'],'doc': employees,
                 'sleepy': ['bashful','doc', 'happy'],'grumpy':[],
                 'bashful': ['dopey']}
secret_word = 'utilitarian'
flip = {'0':'1', '1':'0'}
bit_string = '001110'
flipped = [flip[x] for x in bit_string]

Write out the values of the following expressions, noting errors where appropriate.  Pay attention to your types (use delimiters like `{`, `[`, and `(` appropriately).

```
employees[2:5]
employeeEmail['happy'][1][-1]
employeeEmail[1][1][-1]
employeeEmail['happy']['sleepy'][-1]
secret_word[-5:]
[x < 'j' for x in secret_word]
flipped
```

Write a function which takes two numbers `m` and `n` and returns the result of adding `m` and `n` together and multiplying the result by 3.

Part 5

In [14]:
import numpy as np
x = np.array([5,13,23,47,9])
y = np.ones((5,))
z = np.ones((5,2))

In [20]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [26]:
z[4,1]

1.0

For each of the following expressions, write down what is returned.

In [27]:
x * 2

array([10, 26, 46, 94, 18])

In [28]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [30]:
print(x)
print(y)
x + y

[ 5 13 23 47  9]
[ 1.  1.  1.  1.  1.]


array([  6.,  14.,  24.,  48.,  10.])

In [ ]:
z

In [ ]:
x + z

Explain why you get the result that you get for `x + z`. (Answer: `x` and `z` have incompatible shapes.
`x` is a `1D` array with shape `(5,)`, and `z` is a 2D array with shape `(5,2)`.

In [ ]:
z.shape

Note the following:

In [31]:
x < 20

array([ True,  True, False, False,  True], dtype=bool)

The result above is called a **Boolean array** because it only contains instances of the
type `bool` (`True` and `False`). Such Boolean arrays can be used to index arrays (basically
if they are of the same length).  Using a Boolean array this way is called using a **Boolean mask**.

Using a Boolean mask, write an expression that returns an array containing the members of `x` that
are less than `20`.

In [32]:
x[x<20]

array([ 5, 13,  9])

In [33]:
two_d_array = np.array([[1,2],[2,1],[5,5],[9,4]])

In [34]:
two_d_array

array([[1, 2],
       [2, 1],
       [5, 5],
       [9, 4]])

Write an expression that returns the second row of `two_d_array`.

In [ ]:
two_d_array[1,]

Write an expression that returns `two_d_array` omitting the first row.

Write an expression that returns the following subarray of `two_d_array`.

```
array([[2, 1],
       [5, 5]])
```